-- Insert sample data (optional - you can remove this section if you don't want sample data)
INSERT INTO `students` (`name_chi`, `name_eng`, `nickname`, `short_name`, `gender`, `class`, `status`, `image_path`) VALUES
('陳浩賢', 'Chan, Jayvon', 'NULL', '浩', 'M', '喜樂1', 'Active', 'images/stu/陳浩賢.jpg'),
('張俊生', 'Cheung, Chun Sang', 'NULL', '生', 'M', '喜樂1', 'Active', 'images/stu/張俊生.jpg'),
('曾家業', 'Tsang, Ka Yip', 'NULL', '業', 'M', '喜樂1', 'Active', 'images/stu/曾家業.jpg'),
('陳珮詩', 'Chan, Pui Sze', 'NULL', '詩', 'F', '喜樂1', 'Active', 'images/stu/陳珮詩.jpg'),
('劉華一', 'Liu, Huayi', 'NULL', '華', 'M', '喜樂1', 'Active', 'images/stu/劉華一.jpg'),
('李俊凱', 'LI CHUN HOI', 'NULL', '李俊凱', 'M', '喜樂1', 'Active', 'images/stu/李俊凱.jpg'),

('曾婉鈴', 'Tsang, Yuen Ling', 'NULL', '鈴', 'F', '喜樂2', 'Active', 'images/stu/曾婉鈴.jpg'),
('林國謙', 'Lin, Kwok Him', 'NULL', '國', 'M', '喜樂2', 'Active', 'images/stu/林國謙.jpg'),
('黃淳軒', 'Wong, Shun Hin', 'Aaron', '淳', 'M', '喜樂2', 'Active', 'images/stu/黃淳軒.jpg'),
('', 'Gurung Raya', 'NULL', 'Rg', 'F', '喜樂2', 'Active', 'images/stu/Raya.jpg'),
('', 'Bains Priyansh', 'NULL', 'Pb', 'M', '喜樂2', 'Active', 'images/stu/Priyansh.jpg'),
('吳倬維', 'Ng, Cheuk Wai', '維維', '維', 'M', '喜樂2', 'Active', 'images/stu/吳倬維.jpg'),

('王梓雯', 'Wong, Tsz Man', 'NULL', '雯', 'F', '恩誠1', 'Active', 'images/stu/王梓雯.jpg'),
('吳欣蕾', 'Wu, Xinlei', 'NULL', '蕾', 'F', '恩誠1', 'Active', 'images/stu/吳欣蕾.jpg'),
('袁梓琳', 'Yuen, Tsz Lam', 'NULL', '袁', 'F', '恩誠1', 'Active', 'images/stu/袁梓琳.jpg'),
('藍馨怡', 'Lam, Hing Yi', 'NULL', '馨', 'F', '恩誠1', 'Active', 'images/stu/藍馨怡.jpg'),
('阮文謙', 'Yuen, Man Him', 'Lucas', '阮', 'M', '恩誠1', 'Active', 'images/stu/阮文謙.jpg'),
('鄧宇彬', 'Tang, Yu Bin', 'NULL', '鄧', 'M', '恩誠1', 'Active', 'images/stu/鄧宇彬.jpg'),
('陳思齊', 'Chan, Sze Chai', 'NULL', '齊', 'M', '恩誠1', 'Active', 'images/stu/陳思齊.jpg'),
('余守仁', 'Yu, Wallace Sau Yan', 'NULL', '守', 'M', '恩誠1', 'Active', 'images/stu/余守仁.jpg'),
('', 'Rawat, Vania', 'NULL', 'Vr', 'F', '恩誠1', 'Active', 'images/stu/Vania.jpg'),

('吳庭軒', 'Ung, Ting Hin', 'NULL', '軒', 'M', '恩誠2', 'Active', 'images/stu/吳庭軒.jpg'),
('楊天朗', 'Yeung, Tin Long', 'NULL', '天', 'M', '恩誠2', 'Active', 'images/stu/楊天朗.jpg'),
('鄭善瑜', 'Cheng, Sin Yu', 'NULL', '善', 'M', '恩誠2', 'Active', 'images/stu/鄭善瑜.jpg'),
('曾玄彬', 'Tsang, Alan', 'NULL', '玄', 'M', '恩誠2', 'Active', 'images/stu/曾玄彬.jpg'),
('黃俊熹', 'Wong, Chun Hei', 'NULL', '俊', 'M', '恩誠2', 'Active', 'images/stu/黃俊熹.jpg'),
('鄭保怡', 'Cheng, Po Yee', 'NULL', '保', 'M', '恩誠2', 'Active', 'images/stu/鄭保怡.jpg'),
('李卓謙', 'Lee, Cheuk Him', 'NULL', '卓', 'M', '恩誠2', 'Active', 'images/stu/李卓謙.jpg'),
('鄭喬澧', 'Cheng, Kiu Lai', 'NULL', '澧', 'M', '恩誠2', 'Active', 'images/stu/鄭喬澧.jpg'),
('黃志言', 'Wong, Chi Yin', 'NULL', '言', 'M', '恩誠2', 'Active', 'images/stu/黃志言.jpg'),

('', 'Hyland, Alexander Carl Casagan', 'NULL', 'Ah', 'M', '信望1', 'Active', 'images/stu/Alexander.jpg'),
('陳枳如', 'Chan, Chi Yu', 'NULL', '枳', 'F', '信望1', 'Active', 'images/stu/陳枳如.jpg'),
('周曉瑜', 'Chow, Hiu Yu', 'NULL', '瑜', 'F', '信望1', 'Active', 'images/stu/周曉瑜.jpg'),
('徐浚熙', 'Tsui, Chun Hei', 'NULL', '熙', 'M', '信望1', 'Active', 'images/stu/徐浚熙.jpg'),
('陳泰軒', 'Chen, Tai Hin', 'NULL', '泰', 'M', '信望1', 'Active', 'images/stu/陳泰軒.jpg'),
('王樂林', 'Wong, Lok Lam', 'NULL', '王', 'M', '信望1', 'Active', 'images/stu/王樂林.jpg'),
('盧斯嵐', 'Lo, Sze Nam', 'NULL', '斯', 'F', '信望1', 'Active', 'images/stu/盧斯嵐.jpg'),
('吳卓彥', 'Ng, Cheuk Yin', 'NULL', '彥', 'M', '信望1', 'Active', 'images/stu/吳卓彥.jpg'),
('陳映藍', 'Chan, Ying Laam', 'NULL', '藍', 'F', '信望1', 'Active', 'images/stu/陳映藍.jpg'),

('郭祐男', 'Kwok, Yau Nam', 'NULL', '男', 'M', '信望2', 'Active', 'images/stu/郭祐男.jpg'),
('林家樂', 'Lam, Ka Lok', 'NULL', '家', 'M', '信望2', 'Active', 'images/stu/林家樂.jpg'),
('容景熹', 'Yung, King Hey', 'NULL', '容', 'M', '信望2', 'Active', 'images/stu/容景熹.jpg'),
('于靜妍', 'Yu, Ching Yin', 'NULL', '于', 'F', '信望2', 'Active', 'images/stu/于靜妍.jpg'),
('郭俊賢', 'Kwok, Chun Yin', 'NULL', '賢', 'M', '信望2', 'Active', 'images/stu/郭俊賢.jpg'),
('余信堯', 'Yu, Shun Yiu', 'NULL', '堯', 'M', '信望2', 'Active', 'images/stu/余信堯.jpg'),
('劉惜緣', 'Lau, Sik Yuen', 'NULL', '緣', 'F', '信望2', 'Active', 'images/stu/劉惜緣.jpg'),
('劉倬熙', 'Lau, Cheuk Hei', 'NULL', '倬', 'M', '信望2', 'Active', 'images/stu/劉倬熙.jpg'),
('何沁悠', 'Ho, Sum Yau Alice', 'NULL', '悠', 'F', '信望2', 'Active', 'images/stu/何沁悠.jpg'),

('徐泓智', 'Tsui, Wang Chi', 'NULL', '徐', 'M', '信望3', 'Active', 'images/stu/徐泓智.jpg'),
('袁珮淇', 'Yuen, Pui Ki', 'NULL', '淇', 'F', '信望3', 'Active', 'images/stu/袁珮淇.jpg'),
('蘇楚然', 'So, Cho Yin', 'NULL', '然', 'M', '信望3', 'Active', 'images/stu/蘇楚然.jpg'),
('梁栢豪', 'Leung, Pak Ho', 'NULL', '栢', 'M', '信望3', 'Active', 'images/stu/梁栢豪.jpg'),
('梁恬朗', 'leung, Tim Long', 'NULL', '恬', 'M', '信望3', 'Active', 'images/stu/梁恬朗.jpg'),
('鍾思博', 'Chung, Sze Pok', 'NULL', '博', 'M', '信望3', 'Active', 'images/stu/鍾思博.jpg'),
('陳柏穎', 'Chan, Pak  Wing', 'NULL', '穎', 'F', '信望3', 'Active', 'images/stu/陳柏穎.jpg'),
('陳泓迪', 'Chan, Wang Dik', 'NULL', '迪', 'M', '信望3', 'Active', 'images/stu/陳泓迪.jpg'),

('麥爾諾', 'Mak, Yi Nok', 'NULL', '諾', 'M', '信望4', 'Active', 'images/stu/麥爾諾.jpg'),
('高戩廷', 'Ko, Chin Ting', 'NULL', '戩', 'M', '信望4', 'Active', 'images/stu/高戩廷.jpg'),
('許羽軒', 'Hui, Yu Hin', 'NULL', '羽', 'M', '信望4', 'Active', 'images/stu/許羽軒.jpg'),
('吳承臻', 'Ng, Shing Chun', 'NULL', '承', 'M', '信望4', 'Active', 'images/stu/吳承臻.jpg'),
('呂曉峰', 'Lui, Hiu Fung', 'NULL', '呂', 'M', '信望4', 'Active', 'images/stu/呂曉峰.jpg'),
('蔡瑩', 'Choy, Ying', 'NULL', '蔡', 'F', '信望4', 'Active', 'images/stu/蔡瑩.jpg'),
('陳樂兒', 'Chan, Lok Yee', 'NULL', '兒', 'F', '信望4', 'Active', 'images/stu/陳樂兒.jpg'),
('冼俊賢', 'Sin, Chun Yin', 'NULL', '冼', 'M', '信望4', 'Active', 'images/stu/冼俊賢.jpg'),
('麥仲諭', 'Mak, Chung Yu', 'NULL', '諭', 'M', '信望4', 'Active', 'images/stu/麥仲諭.jpg'),

('李昫賢', 'Lee, Hui Yin Ethan', 'NULL', '李', 'M', '和平1', 'Active', 'images/stu/李昫賢.jpg'),
('', 'Stephens, Viliame Lutumailagi', 'NULL', 'Vs', 'M', '和平1', 'Active', 'images/stu/Stephens.jpg'),
('李浠鉖', 'Li, Hei Tung', 'NULL', '鉖', 'F', '和平1', 'Active', 'images/stu/李浠鉖.jpg'),
('陳逸朗', 'Chan, Yat Long', 'NULL', '逸', 'M', '和平1', 'Active', 'images/stu/陳逸朗.jpg'),
('陳治仁', 'Chen, Chi Yan Jerry', 'NULL', '治', 'M', '和平1', 'Active', 'images/stu/陳治仁.jpg'),
('李昆達', 'Li, Kunda Linda', 'NULL', '昆', 'F', '和平1', 'Active', 'images/stu/李昆達.jpg'),
('莊雅晴', 'Chuang, Nga Ching', 'NULL', '晴', 'F', '和平1', 'Active', 'images/stu/莊雅晴.jpg'),
('謝元暘', 'Tse Yuen Yeung', 'NULL', '暘', 'M', '和平1', 'Active', 'images/stu/謝元暘.jpg'),
('李浚弘', 'Li, Jun Hong', 'NULL', '李浚弘', 'M', '和平1', 'Active', 'images/stu/李浚弘.jpg'),
('單妙蓮', 'SIN, MIU LIN', 'NULL', '單妙蓮', 'F', '和平1', 'Active', 'images/stu/單妙蓮.jpg'),

('', 'Naurin, Ullah Zaina Naurin, Ullah Zaina ', 'NULL', 'Zn', 'F', '和平2', 'Active', 'images/stu/Naurin.jpg'),
('林鉦喬', 'Lam, Ching Kiu', 'NULL', '鉦', 'M', '和平2', 'Active', 'images/stu/林鉦喬.jpg'),
('肖詩樺', 'Xiao, Sze Wa', 'NULL', '肖', 'F', '和平2', 'Active', 'images/stu/肖詩樺.jpg'),
('鄭曉彤', 'Cheng, Hiu Tung', 'NULL', '曉', 'F', '和平2', 'Active', 'images/stu/鄭曉彤.jpg'),
('朱雪琳', 'Chu, Suet Lam Shirlyn', 'NULL', '朱', 'F', '和平2', 'Active', 'images/stu/朱雪琳.jpg'),
('黃弘瀚', 'Wong, Wang Hon Wesley', 'NULL', '瀚', 'M', '和平2', 'Active', 'images/stu/黃弘瀚.jpg'),
('胡亦琛', 'Wu, Yik Sum Dixon', 'NULL', '琛', 'M', '和平2', 'Active', 'images/stu/胡亦琛.jpg'),
('孔政鵬', 'Hung, Ching Pang', 'Pang Pang', '孔', 'M', '和平2', 'Active', 'images/stu/孔政鵬.jpg'),
('巢永漮', 'Chau, Brendon Wing Hong', '巢巢', '巢', 'M', '和平2', 'Active', 'images/stu/巢永漮.jpg'),
('鍾皓霖', 'Zhong, Haolin', 'NULL', '皓', 'M', '和平2', 'Active', 'images/stu/鍾皓霖.jpg'),

('高曉澄', 'Ko, Hiu Ching', 'NULL', '高', 'F', '和平3', 'Active', 'images/stu/高曉澄.jpg'),
('葉思行', 'Yip, Sze Hang', 'NULL', '思', 'M', '和平3', 'Active', 'images/stu/葉思行.jpg'),
('梁月怡', 'Leung, Yuet Yi', 'NULL', '怡', 'F', '和平3', 'Active', 'images/stu/梁月怡.jpg'),
('鄭彥滔', 'Cheng, Yin To', 'NULL', '鄭', 'M', '和平3', 'Active', 'images/stu/鄭彥滔.jpg'),
('余恩誠', 'Yu, Yan Shin', 'NULL', '余', 'M', '和平3', 'Active', 'images/stu/余恩誠.jpg'),
('陳槺霖', 'Chan, Hong Lam', 'NULL', '霖', 'M', '和平3', 'Active', 'images/stu/陳槺霖.jpg'),
('陳紫縈', 'Chan, Tsz Ying', 'NULL', '紫', 'F', '和平3', 'Active', 'images/stu/陳紫縈.jpg'),
('李偉豪', 'Li, Wai Ho Sam', 'NULL', '偉', 'M', '和平3', 'Active', 'images/stu/李偉豪.jpg'),
('吳浩坤', 'Ng, Ho Kwan Jesse', 'NULL', '坤', 'M', '和平3', 'Active', 'images/stu/吳浩坤.jpg'),
('黃信一', 'Wong, Elijah', 'NULL', '信', 'M', '和平3', 'Active', 'images/stu/黃信一.jpg'),

('各山', 'Singh, Sangha Gurshan', 'NULL', '各', 'M', '禮智1', 'Active', 'images/stu/各山.jpg'),
('曾慶淳', 'Tsang, Hing Shun', 'NULL', '慶', 'M', '禮智1', 'Active', 'images/stu/曾慶淳.jpg'),
('李凱彤', 'Lee, Hoi Tung Alicia', 'NULL', '彤', 'F', '禮智1', 'Active', 'images/stu/李凱彤.jpg'),
('張晉硯', 'Cheung, Henry Chun Yin', 'NULL', '硯', 'M', '禮智1', 'Active', 'images/stu/張晉硯.jpg'),
('劉彥廷', 'Lau, Clinton', 'NULL', '廷', 'M', '禮智1', 'Active', 'images/stu/劉彥廷.jpg'),
('陳昉得', 'Chan, Fong Tak', 'NULL', '昉', 'M', '禮智1', 'Active', 'images/stu/陳昉得.jpg'),
('許鵬程', 'Hui, Kurt Martin Robles', 'NULL', '鵬', 'M', '禮智1', 'Active', 'images/stu/許鵬程.jpg'),
('梁均烺', 'Leung, Kwan Long', 'NULL', '烺', 'M', '禮智1', 'Active', 'images/stu/梁均烺.jpg'),
('韓一一', 'Han, Yiyi', 'NULL', '一', 'F', '禮智1', 'Active', 'images/stu/韓一一.jpg'),
('馬嘉駺', 'Ma, Ka Leung', 'NULL', '駺', 'M', '禮智1', 'Active', 'images/stu/馬嘉駺.jpg'),

('阮天行', 'Yuen, Tin Hang', 'NULL', '行', 'M', '愛德1', 'Active', 'images/stu/阮天行.jpg'),
('鄺明得', 'Kwong, Ming Tak', 'NULL', '得', 'M', '愛德1', 'Active', 'images/stu/鄺明得.jpg'),
('張誥麟', 'Cheung, Ko Lun', 'NULL', '麟', 'M', '愛德1', 'Active', 'images/stu/張誥麟.jpg'),
('鄭靜文', 'Cheng, Ching Man', 'NULL', '靜', 'F', '愛德1', 'Active', 'images/stu/鄭靜文.jpg'),
('鄧焯琦', 'Tang, Cheuk Kei', 'NULL', '琦', 'F', '愛德1', 'Active', 'images/stu/鄧焯琦.jpg'),
('陳熹橋', 'Chan, Hei Kiu Ethan', 'NULL', '橋', 'M', '愛德1', 'Active', 'images/stu/陳熹橋.jpg'),

('陳頌仁', 'Chan, Chung Yan', 'NULL', '仁', 'M', '愛德2', 'Active', 'images/stu/陳頌仁.jpg'),
('葉凱琳', 'Yip, Danika', 'NULL', '琳', 'F', '愛德2', 'Active', 'images/stu/葉凱琳.jpg'),
('陳樹兆', 'Tran, Shu Shau', '樹兆', '兆', 'M', '愛德2', 'Active', 'images/stu/陳樹兆.jpg'),
('曾振軒', 'Tsang, Henry', 'NULL', '振', 'M', '愛德2', 'Active', 'images/stu/曾振軒.jpg'),
('陳思龍', 'Chan, Sze Lung', 'NULL', '龍', 'M', '愛德2', 'Active', 'images/stu/陳思龍.jpg'),
('吳梓宇', 'Ng, Pierson Sy', 'NULL', '宇', 'M', '愛德2', 'Active', 'images/stu/吳梓宇.jpg'),
('唐子濂', 'Tong, Tsz Lim', 'NULL', '唐', 'M', '愛德2', 'Active', 'images/stu/唐子濂.jpg'),
('叶子睿', 'Ye, Zirui', 'NULL', '睿', 'M', '愛德2', 'Active', 'images/stu/叶子睿.jpg');

